### ISSUE TITLE
Hola. Fa més de dos anys que aquest repositori no s'actualitza. ¿És per algun motiu concret?

### ISSUE THREAD

**Issue by q2dg** [edutec/Snapi-AMB#1]
Bàsicament voldria saber si és que es considera completament acabat i per això no necessita canvis o bé si és que no està sent mantingut. Més que res per tenir-ho en compte per projectes propis a mig plaç
Moltes gràcies.

**Comment by bromagosa** [comment]
Aquest repositori és per una versió concreta d'Snapi<i>!</i> que havia de quedar congelada i no canviarà més. El repositori correcte d'Snapi<i>!</i> és [aquest](https://github.com/edutec/Snapi).

Salut!

**Comment by q2dg** [comment]
Ah, oh, disculpeu!
Merci!
